### PR TITLE
es6 module example added

### PR DESCRIPTION
**Pull request by capaj**
I thought it would be nice to show the es6 module in the example.
also a question- when I leave the make-monster as it was, function is not imported in main.js, do you know why?

### CODE REVIEW

**Comment by thlorenz** [comment]
Does this actually work? Keep in mind we are browserifying this.

Did you build and load it with that change into the browser and saw the expected output?

**Comment by capaj** [comment]
yes it does. When run, I see:

starting es6ify demo E:\WebstormProjects\es6ify\example\src\main.js:1
tmp is undefined:  true E:\WebstormProjects\es6ify\example\src\features\block-scope.js:10
hello, world E:\WebstormProjects\es6ify\example\src\features\destructuring.js:3
generating tree labels in order: E:\WebstormProjects\es6ify\example\src\features\generators.js:26
a E:\WebstormProjects\es6ify\example\src\features\generators.js:30
b E:\WebstormProjects\es6ify\example\src\features\generators.js:30
c E:\WebstormProjects\es6ify\example\src\features\generators.js:30
d E:\WebstormProjects\es6ify\example\src\features\generators.js:30
e E:\WebstormProjects\es6ify\example\src\features\generators.js:30
f E:\WebstormProjects\es6ify\example\src\features\generators.js:30
g E:\WebstormProjects\es6ify\example\src\features\generators.js:30
An instance of Foo says hi from its .toString()! E:\WebstormProjects\es6ify\example\src\features\classes.js:8
I am the cookie monster E:\WebstormProjects\es6ify\example\src\main.js:23
attacking cookie thief E:\WebstormProjects\es6ify\example\src\make-monster.js:7
element: 1 E:\WebstormProjects\es6ify\example\src\features\iterators.js:3
element: 2 E:\WebstormProjects\es6ify\example\src\features\iterators.js:3
element: 3 E:\WebstormProjects\es6ify\example\src\features\iterators.js:3
name: Heinz Muelleimer, codes: Cobol, lives in: Germany E:\WebstormProjects\es6ify\example\src\features\default-parameters.js:2
name: Thorsten Lorenz, codes: JavaScript, lives in: USA E:\WebstormProjects\es6ify\example\src\features\default-parameters.js:2
name: Grandpa Otto, codes: Java, lives in: USA E:\WebstormProjects\es6ify\example\src\features\default-parameters.js:2
list animals has the following items E:\WebstormProjects\es6ify\example\src\features\rest-parameters.js:2
cat E:\WebstormProjects\es6ify\example\src\features\rest-parameters.js:3
dog E:\WebstormProjects\es6ify\example\src\features\rest-parameters.js:3
zebra E:\WebstormProjects\es6ify\example\src\features\rest-parameters.js:3
giraffe E:\WebstormProjects\es6ify\example\src\features\rest-parameters.js:3
lion E:\WebstormProjects\es6ify\example\src\features\rest-parameters.js:3
3 + 4 = 7 E:\WebstormProjects\es6ify\example\src\features\spread-operator.js:3
a messsage from your personal arrow function E:\WebstormProjects\es6ify\example\src\features\arrow-functions.js:1

**Comment by capaj** [comment]
oh sry, I forgot to comit the updated npm dependencies to different branch. Since the updated dependencies broke your test, you should not merge this pull request. So either just fix your tests, or just close this request.

**Comment by thlorenz** [comment]
Well if things work for you and the tests are the only remaining obstacle, would you have a stab at fixing things so they don't break?
If the tests are fine before and break due to the code you added why do you think its the tests that need fixing? Could you please change your contributions so the tests don't break in the first place?

Thanks.

**Pull request closed without merging**
