### PR TITLE
Moved es6 examples into readme

### PR DESCRIPTION
**Pull request by pfrazee**
When I check out es6ify, I tend to look for code examples of what's supported. Since I'm not always sure what the es6 features are by name, it helps to have them written out for me.

I'd suggest the same for the gh-pages index.html. Alternatively, make the link to Traceur's readme (which has the examples listed) more prominent.

### CODE REVIEW

**Comment by thlorenz** [comment]
kinda like it although it makes README much larger.
Could we compromise and include the source, but also leave the links to the examples (in `example/src/feature`) folder?

That way people understand that they can actually try them.

The ones that 'need fixing' we can just leave for now (they weren't linked before either).
If you want you could add examples for these inside `example/src/feature` and included them in demo and tests.
However that's not needed right now.

**Comment by pfrazee** [comment]
> Could we compromise and include the source, but also leave the links to the examples (in example/src/feature) folder?

Works for me!

**Comment by thlorenz** [comment]
Cool I'll pull this and update gh-pages as well.
Thanks.

**Comment by thlorenz** [comment]
Thanks, published with `1.0.2` to get these also on npmjs.org.

**Pull request closed without merging**
