### PR TITLE
update traceur to 0.0.46

### PR DESCRIPTION
**Pull request by PatrickJS**

### CODE REVIEW

**Comment by thlorenz** [comment]
This PR fails because this version of traceur has not been published to npm as [you can easily see](https://www.npmjs.org/package/traceur).

```
npm ERR! Error: version not found: 0.0.46 : traceur/0.0.46
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:254:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:192:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

Please apply these fixes on your machine in the future and run tests afterwards instead of a patch in github. My time is limited and I expect contributors to do their part to help me maintain these modules with the least overhead possible.

Therefore I will consider just ignoring `patch-x` PRs that have been created on github in the future.

**Comment by Raynos** [comment]
or setup travis for pull requests so you dont have to manually verify tests.

**Comment by thlorenz** [comment]
@Raynos I thought this is setup automatically? What step am I missing here?

screen shot 2014-06-21 at 9 36 31 pm

**Comment by Raynos** [comment]
not sure. but if travis failed for this PR travisbot would come in and leave a comment saying it failed,

**Pull request closed without merging**
