### PR TITLE
Fix output of destructuring example (I think)

### PR DESCRIPTION
**Pull request by jamesmanning**

### CODE REVIEW

**Comment by thlorenz** [comment]
Could you please provide a before/after screenshot?

I can't judge if the fix is appropriate since I can't see what this changes.

Thanks

**Comment by jamesmanning** [comment]
The code in the example is:

var [a, [b], c, d] = ['hello', [', ', 'junk'],
['world']];console.log(a + b + c); // hello world

AFAICT, since the value in b will be ', ' the actual console.log will have
a comma in it (so, "hello, world" instead of "hello world")

Adding that comma (assuming it's the correct change) is all that's needed.
 If you can add that comma, then feel free to ignore this PR. :)

**Comment by thlorenz** [comment]
Repasted code here for readability:

``` js
var [a, [b], c, d] = ['hello', [', ', 'junk'],['world']];
console.log(a + b + c); // hello world
```

Yes, you are right, actually running the code [here](http://thlorenz.github.io/es6ify/) and opening dev tools confirmed the comma is there.

Merging this in, thanks.

**Comment by thlorenz** [comment]
Ok merged, but now it's highlighted in yellow.
If you want please fix it and submit another PR, otherwise I'll leave this for now until the next release since it's not such a big deal IMO.

**Comment by thlorenz** [comment]
Never mind I fixed the highlighting, all that was needed actually was to add that comma there instead of changing entire span.

**Pull request merged**
