### PR TITLE
Fix using sourcemap generator when there is no sourcemap

### LINKED ISSUE #64: Turning off sourcemaps fails
Per default I get the following for every required module
//# sourceMappingURL=< compileOutput>

When I try to turn off source maps
es6ify.traceurOverrides = { sourceMaps: false };

I get:
TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]

Is there a way to turn of source maps?

I am currently running through gulp.
browserify: 4.2.3

### PR DESCRIPTION
**Pull request by guzart**
Fixes #64

### CODE REVIEW

**Comment by domenic** [comment]
Probably should have a test...

**Comment by Aaike** [comment]
:+1: This works , im using it to disable sourcemaps with `traceurOverrides = { sourceMaps: false }`

please merge it :)

**Comment by domenic** [comment]
Needs a test before it can be merged

**Comment by thlorenz** [comment]
Yeah, just add a test case for exactly the situation you describe to turn off sourcemaps.

**Comment by guzart** [comment]
Test case added. I think it makes sense for the test to be on the transform instead of the bundle.

**Comment by domenic** [comment]
Thanks, merged as d375cf90980ff90e2a3ddddd1909f2512eb52a6b

**Pull request closed without merging**
